IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/v0.1.5
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = ADS_Testing
PROJECT_PATH := ../../ADS_Testing/ADS_Testing.tsproj
PLC = TestProj

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
